name: Tests

on:
  push:
    paths:
      - "src/**"
      - "dist/**"
      - ".github/**"
      - "action.yml"
      - "package.json"
      - "jest.config.js"
      - "package-lock.json"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: "**/node_modules"
          key: node-12-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Tests
        run: npm run test
      - uses: weyheyhey/create-dotenv-action@v1
        with:
          filename: ".env.production"
        env:
          ^TEST_ENV_ONE: value-one
          ^TEST_ENV_TWO: value-two
          TEST_ENV_THREE: value-three
      - name: Read the result
        run: cat ./.env.production
